### ISSUE TITLE
cannot search using a type signature in sherlodoc

### ISSUE THREAD

**Issue by UnixJunkie** [art-w/sherlocode#3]
e.g.
```ocaml
'a -> 'a
```

**Comment by UnixJunkie** [comment]
even if the search is approximate, it would be better than not returning anything

**Comment by UnixJunkie** [comment]
Look at the gold standard, for comparison:
https://hoogle.haskell.org/

**Comment by art-w** [comment]
Hello! Yes the query syntax is not super intuitive, you need to add a colon to search by type [`: 'a -> 'a`](https://doc.sherlocode.com/?q=%3A%20%27a%20-%3E%20%27a) (and I'm afraid the sorting also needs work as it prefers the less nested functions `min` and `max` despite the exact match on `Fun.id`)
I have some ideas for dropping the colon requirement, I'll try again as the first attempt was producing confusing results. I still want to keep the colon for advanced queries though, it really helps to refine the search results without introducing ambiguity.

**Comment by UnixJunkie** [comment]
maybe people will want some regexp symbols.
E.g.
```ocaml
: 'a -> 'a$
```

**Comment by art-w** [comment]
Hm if the sorting of results gets fixed, I'm not sure I understand the need for regexes? The type search is not doing a string search, it's working on the type AST provided by odoc. The assumption is that the user doesn't know the exact type of the function he's looking for, but can provide the required ingredients:

- [`: 'a t * key -> 'a`](https://doc.sherlocode.com/?q=%3A%20%27a%20t%20*%20key%20-%3E%20%27a) will find the isomorphic `key -> 'a t -> 'a` results... but you could also just do [`Map : t -> 'a`](https://doc.sherlocode.com/?q=Map%20%3A%20t%20-%3E%20%27a) which is even more fuzzy
- [`Parany : ('a -> 'b -> 'b) -> 'a list -> 'b -> 'b`](https://doc.sherlocode.com/?q=Parany%20%3A%20(%27a%20-%3E%20%27b%20-%3E%20%27b)%20-%3E%20%27a%20list%20-%3E%20%27b%20-%3E%20%27b) still finds the fold even though it's missing arguments and the accumulator is not in the right place

It's definitively not perfect, but I find it satisfying to get quick answers without breaking out of the flow to craft the perfect query :)

**Comment by UnixJunkie** [comment]
yes, regexes are just useful for string searches.
I did not know that your type searches were different.

**Comment by art-w** [comment]
Yeah I could not resist the play on words when naming sherl**odoc** :P ... but it actually creates a lot of confusion with sherlocode (which is all about regexes [`: 'a -> 'a\$`](https://sherlocode.com/?q=%3A%20%27a%20-%3E%20%27a%5C%24), and answering "how do people write ocaml code" rather than "how to discover useful functions")

Anyway, thanks for the feedback! It will be useful to clarify the homepage in the future and make `:` optional like Hoogle :)

**Comment by bbatsov** [comment]
> Yeah I could not resist the play on words when naming sherlodoc :P

Now I know! 😆 Naming is hard, but I think you did pretty well with this one!

**Comment by art-w** [comment]
Thanks! I added a tiny heuristic inspired by Hoogle for type search without a `:` prefix

**Comment by UnixJunkie** [comment]
I don't know what the heuristic is but searching 'a -> 'a makes it appear quite late in the results list.
My advice:
transform all type signatures as multisets.
E.g. 'a -> 'a becomes "type 'a is seen two times".
Then compare them using the Tanimoto/Jaccard coefficient.
The higher the score, the higher in the ranked list.

**Comment by art-w** [comment]
Yes, there's currently no sorting but a global order (that favors documented, less module nested `M.N.foo`, shorter names / type signature, and a huge bonus for the Stdlib)... As a result of the module nesting heuristic, `Stdlib.max` will appear before `Stdlib.Fun.id` in all queries. (The multiset is already in place, but the search is fuzzily looking for "at least two `'a`" and not a strict "exactly two")
This is clearly not great! I plan to work on this :)

**Comment by UnixJunkie** [comment]
From your description, sorting looks more important; global order could be used only to sort
answers with the same ranking score.

**Comment by art-w** [comment]
I've added a sorting algorithm, the results should now appear in a more natural order with respect to your queries :) But let me know if you can find some example queries that could still be improved!

**Comment by UnixJunkie** [comment]
I tried this query:
t: 'a -> 'a
What comes at the top is not what I expect.

**Comment by UnixJunkie** [comment]
In the returned results, it is quite nice that we can click to jump into the code.

**Comment by art-w** [comment]
I'm not sure if you tried searching in the code grepping tool (https://sherlocode.com/?q=t%3A%20%27a%20-%3E%20%27a which has links to the source code) or the documentation type search (https://doc.sherlocode.com/?q=t%3A%20%27a%20-%3E%20%27a which has links to the documentation). Only the later one has sorting :)

**Comment by UnixJunkie** [comment]
Ok, with the second link, results are not too bad.
