### ISSUE TITLE
sources for sherlodoc

### ISSUE THREAD

**Issue by Khady** [art-w/sherlocode#4]
I discovered sherlodoc from https://discuss.ocaml.org/t/does-this-partition-function-have-a-name/10581 and was impressed. I wanted to try to run it on a personal project, but from what I can see this project only contains sherlocode. Am I missing something or would it be possible to release the sources of sherlodoc?

Thanks for the great project

**Comment by art-w** [comment]
Sorry you are not missing anything, I never completed the sherlodoc experiment and its code is a mess ^^' . Nevertheless, I'll push the sources in the coming days and send you the link :)

**Comment by bbatsov** [comment]
It'd be nice to also add something like `(* Read the source, fork and contribute to [art-w/sherlocode](https://github.com/art-w/sherlocode) *)` there as well.

**Comment by art-w** [comment]
The sources are now available on a [specific repository for sherlodoc](https://github.com/art-w/sherlodoc) with some description on how to run it yourself :) Please reach out if you encounter any problems!

**Comment by Khady** [comment]
Thanks!
