### ISSUE TITLE
Use OCaml 4.14 for Sherlodoc

### ISSUE THREAD

**Issue by bbatsov** [art-w/sherlocode#5]
I've noticed that currently it uses the older OCaml 4.12. Not sure why the exact variant is https://ocaml.org/p/ocaml-variants/4.12.0+domains - I'm relatively new to OCaml and I don't quite get what all those variants of the mainline release are (I assume they are just the mainline stuff + some extra features or something along those lines).

**Comment by art-w** [comment]
Ha yes, this is an unfortunate accident as it is the closest thing I have of the stdlib with nice links to the ocaml.org documentation (the variant 4.12+domains is indeed the mainline + some extra stuff, so it's not "wrong" but it is confusing!)
I'll try to switch to 4.14 asap, but there are some technical issues getting in the way atm...

**Comment by art-w** [comment]
We now index the OCaml 5.1.0 Stdlib and point to the official documentation for the links :) (so the hack of using a weird `ocaml-variants` is gone!)
