### ISSUE TITLE
Links in docstrings are hot handled properly by sherlodoc

### ISSUE THREAD

**Issue by bbatsov** [art-w/sherlocode#6]
E.g. here:

![image](https://user-images.githubusercontent.com/103882/197332716-415b150e-7432-4b28-987e-293d56bbe6f4.png)

As you can see the link to `map` is completely missing:

![image](https://user-images.githubusercontent.com/103882/197332740-ee449c78-4b4d-4721-af4c-5535c6bf8283.png)

**Comment by art-w** [comment]
Thanks for the easy to reproduce example! I believe it should work a bit better now :)

**Comment by bbatsov** [comment]
Yep, it's better now, although long-term I guess it'd be ideal if the doc links appear as links in sherlodoc as well.

Thanks for the quick fix! 🙇‍♂️

**Comment by art-w** [comment]
The latest version still has issues with links within the documentation comments (the links are there but they don't point to a correct url...) We have a new issue https://github.com/art-w/sherlodoc/issues/13 to keep track of this in the sherlodoc repo where it might be easier to find if others run into this :)
