### ISSUE TITLE
Duplicated / in code URLs 

### ISSUE THREAD

**Issue by bbatsov** [art-w/sherlocode#7]
All URLs to sources look like this https://gitlab.inria.fr/why3/why3/-/blob/master//src/session/termcode.ml#L1068 (note the `master//src` part)

Basically it seems that an extra / is appended after repo branch path.

**Comment by art-w** [comment]
Oh good catch, thanks! It should be fixed now (but it might require a `ctrl-r` browser refresh for previously cached queries ^^)
